// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"ai_invest/repository/websocket"
)

// Injectors from wire.go:

func Init() (*Container, error) {
	longBridgeWS := websocket.NewLongBridge()
	container := &Container{
		LongBridgeWSClient: longBridgeWS,
	}
	return container, nil
}

// wire.go:

type Container struct {
	LongBridgeWSClient websocket.LongBridgeWS
}

func (c *Container) GetLongBridgeWSClient() websocket.LongBridgeWS {
	return c.LongBridgeWSClient
}
