// Code generated by Kitex v0.12.1. DO NOT EDIT.

package aiinvestrpcservice

import (
	rpc "ai_invest/kitex_gen/rpc"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Test": kitex.NewMethodInfo(
		testHandler,
		newAiInvestRPCServiceTestArgs,
		newAiInvestRPCServiceTestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	aiInvestRPCServiceServiceInfo                = NewServiceInfo()
	aiInvestRPCServiceServiceInfoForClient       = NewServiceInfoForClient()
	aiInvestRPCServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return aiInvestRPCServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return aiInvestRPCServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return aiInvestRPCServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "AiInvestRPCService"
	handlerType := (*rpc.AiInvestRPCService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "rpc",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.12.1",
		Extra:           extra,
	}
	return svcInfo
}

func testHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rpc.AiInvestRPCServiceTestArgs)
	realResult := result.(*rpc.AiInvestRPCServiceTestResult)
	success, err := handler.(rpc.AiInvestRPCService).Test(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newAiInvestRPCServiceTestArgs() interface{} {
	return rpc.NewAiInvestRPCServiceTestArgs()
}

func newAiInvestRPCServiceTestResult() interface{} {
	return rpc.NewAiInvestRPCServiceTestResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Test(ctx context.Context, req *rpc.TestRequest) (r *rpc.TestResponse, err error) {
	var _args rpc.AiInvestRPCServiceTestArgs
	_args.Req = req
	var _result rpc.AiInvestRPCServiceTestResult
	if err = p.c.Call(ctx, "Test", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
